### ISSUE TITLE
dev_requirements.txt is misleading

### ISSUE THREAD

**Issue by JAORMX** [mathias-nyman/pyrelp#1]
Usually (or at least the projects that I've seen) requirements.txt, or what I thought dev_requirements.txt is a file that contains the python dependencies that will eventually be fetched by pip. I recommend you add these dependencies that you put there to the README or CONTRIBUTING files, and leave this sort of file for your python-related requirements.

**Comment by JAORMX** [comment]
On the other hand, it seems that as a dev-requirement autotools and libtool are missing

**Comment by JAORMX** [comment]
You should also add libgnutls-dev (in Ubuntu... it probably has a different name in Arch) to the dependency list.

**Comment by mathias-nyman** [comment]
Thanks for the feedback! Moved the dev dependencies to README. Also libnutls-dev is no longer a dev dependency.
