### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by serathius** [mathias-nyman/pyrelp#2]
Hi, great job on wrapper it works really well. 
I'm considering usage of this package in for production logs. But the main issue is lack of python3 support. 

I don't know anything about C extensions. 
But maybe dummy extension module now supports python3. 
I would really love to use relp in production, and I would be grateful for python3 compatibility.

**Comment by mathias-nyman** [comment]
Hey, sorry for not getting back on this sooner.

I don't have an immediate need for python3 support for pyrelp at the moment. I am not absolutely sold on the idea of trying to support python2 _and_ python3 at the same time. The setuptools trickery is already at 5000 (building librelp as part of the package) :)

I could merge a pull request if the implementation looks clean.

RE production usage: note that TLS functionality of librelp is not wrapped. Depending on your network layout it may be a show-stopper for sending stuff in cleartext.. That said, wrapping the librelp TLS functions would be a very easy contribution for someone.
